# Generated by Django 6.0.4 on 2026-04-15 03:32

from decimal import Decimal
from django.db import migrations, models


def backfill_amount_received(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    for payment in Payment.objects.select_related('invoice').all():
        if payment.amount_received == Decimal('0.00') and payment.invoice_id:
            payment.amount_received = payment.invoice.amount
            payment.save(update_fields=['amount_received'])


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('card', 'Card'), ('ewallet', 'E-Wallet'), ('other', 'Other')], default='bank_transfer', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(backfill_amount_received, noop),
    ]
