# Generated by Django 6.0.4 on 2026-04-13 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_sessions', '0001_initial'),
        ('members', '0002_admissionapplication_progressreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('video_proof', models.FileField(blank=True, upload_to='session_feedback_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_feedback_entries', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_feedback_entries', to='members.member')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='club_sessions.trainingsession')),
            ],
            options={
                'ordering': ['-training_session__session_date', 'member__full_name'],
                'constraints': [models.UniqueConstraint(fields=('training_session', 'member'), name='unique_feedback_per_member_per_session')],
            },
        ),
    ]
