# Generated by Django 6.0.4 on 2026-04-13 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_sessions', '0002_sessionfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('pro', 'Pro')], default='beginner', max_length=20)),
                ('week_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('warm_up_plan', models.TextField()),
                ('technical_focus', models.TextField()),
                ('tactical_focus', models.TextField()),
                ('coaching_cues', models.TextField()),
                ('homework', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_weekly_syllabi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['track', 'week_number'],
                'constraints': [models.UniqueConstraint(fields=('track', 'week_number'), name='unique_syllabus_track_week')],
            },
        ),
    ]
