# Generated by Django 6.0.4 on 2026-04-13 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_sessions', '0003_weeklysyllabus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPlannerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('user_prompt', models.TextField()),
                ('assistant_response', models.TextField()),
                ('source', models.CharField(choices=[('ollama', 'Ollama'), ('fallback', 'Rule-based fallback')], default='ollama', max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_session_plans', to=settings.AUTH_USER_MODEL)),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_entries', to='club_sessions.trainingsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
