# Generated by Django 6.0.4 on 2026-04-13 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_sessions', '0004_sessionplannerentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklysyllabus',
            name='assessment_focus',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklysyllabus',
            name='coach_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklysyllabus',
            name='month_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklysyllabus',
            name='phase_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='weeklysyllabus',
            name='success_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SyllabusStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('focus', models.TextField()),
                ('learning_standard_items', models.TextField(help_text='One learning standard per line.')),
                ('performance_band_items', models.TextField(help_text='One performance band per line.')),
                ('coach_hints', models.TextField(blank=True)),
                ('assessment_focus', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_syllabus_standards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['template__track', 'sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='weeklysyllabus',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_units', to='club_sessions.syllabusstandard'),
        ),
        migrations.CreateModel(
            name='SyllabusTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('pro', 'Pro')], default='beginner', max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('source_document_name', models.CharField(blank=True, max_length=255)),
                ('curriculum_year_label', models.CharField(default='Year 1', max_length=100)),
                ('annual_goal', models.TextField()),
                ('year_end_outcomes', models.TextField()),
                ('assessment_approach', models.TextField(blank=True)),
                ('assessment_methods', models.TextField(blank=True)),
                ('curriculum_values', models.TextField(blank=True)),
                ('annual_phase_notes', models.TextField(blank=True)),
                ('ai_planner_instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_syllabus_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['track'],
            },
        ),
        migrations.AddField(
            model_name='syllabusstandard',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='club_sessions.syllabustemplate'),
        ),
        migrations.AddField(
            model_name='weeklysyllabus',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_units', to='club_sessions.syllabustemplate'),
        ),
        migrations.AddConstraint(
            model_name='syllabusstandard',
            constraint=models.UniqueConstraint(fields=('template', 'code'), name='unique_syllabus_standard_code_per_template'),
        ),
    ]
