# Generated by Django 6.0.4 on 2026-04-15 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_default_syllabus_root(apps, schema_editor):
    SyllabusRoot = apps.get_model("club_sessions", "SyllabusRoot")
    SyllabusTemplate = apps.get_model("club_sessions", "SyllabusTemplate")
    WeeklySyllabus = apps.get_model("club_sessions", "WeeklySyllabus")
    TrainingSession = apps.get_model("club_sessions", "TrainingSession")

    default_root, created = SyllabusRoot.objects.get_or_create(
        code="core_academy_syllabus",
        defaults={
            "name": "Core Academy Syllabus",
            "description": "Default syllabus structure migrated from the academy's original single-root curriculum.",
            "is_active": True,
            "is_default": True,
        },
    )
    if not created and not default_root.is_default:
        default_root.is_default = True
        default_root.save(update_fields=["is_default"])
    SyllabusRoot.objects.exclude(pk=default_root.pk).filter(is_default=True).update(is_default=False)

    SyllabusTemplate.objects.filter(root__isnull=True).update(root=default_root)
    WeeklySyllabus.objects.filter(root__isnull=True).update(root=default_root)
    TrainingSession.objects.filter(syllabus_root__isnull=True).update(syllabus_root=default_root)


class Migration(migrations.Migration):

    dependencies = [
        ('club_sessions', '0005_weeklysyllabus_assessment_focus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='syllabustemplate',
            options={'ordering': ['root__name', 'track', 'name']},
        ),
        migrations.AlterModelOptions(
            name='weeklysyllabus',
            options={'ordering': ['root__name', 'track', 'week_number']},
        ),
        migrations.RemoveConstraint(
            model_name='weeklysyllabus',
            name='unique_syllabus_track_week',
        ),
        migrations.AlterField(
            model_name='syllabustemplate',
            name='track',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('pro', 'Pro')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='syllabusroot',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_syllabus_roots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syllabustemplate',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='club_sessions.syllabusroot'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='syllabus_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='club_sessions.syllabusroot'),
        ),
        migrations.AddField(
            model_name='weeklysyllabus',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_units', to='club_sessions.syllabusroot'),
        ),
        migrations.RunPython(seed_default_syllabus_root, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='syllabustemplate',
            constraint=models.UniqueConstraint(fields=('root', 'track'), name='unique_syllabus_root_track'),
        ),
        migrations.AddConstraint(
            model_name='weeklysyllabus',
            constraint=models.UniqueConstraint(fields=('root', 'track', 'week_number'), name='unique_syllabus_root_track_week'),
        ),
    ]
