# Generated by Django 6.0.4 on 2026-04-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_sessions', '0010_coachavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='last_rescheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
