# Generated by Django 6.0.4 on 2026-05-06 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_sessions', '0011_attendancerecord_last_rescheduled_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='coaches',
            field=models.ManyToManyField(blank=True, help_text='All coaches running this session (lead coach + co-coaches).', related_name='coached_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
