# Generated by Django 6.0.4 on 2026-04-13 02:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_product'),
        ('members', '0003_admissionapplication_playing_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_invoice_period_per_member',
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('registration', 'Registration Fee'), ('monthly', 'Monthly Fee'), ('misc', 'Miscellaneous')], default='monthly', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('member', 'period', 'invoice_type'), name='unique_invoice_period_type_per_member'),
        ),
    ]
