# Generated by Django 6.0.4 on 2026-04-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_invoice_unique_invoice_period_per_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_onboarding_fee',
            field=models.BooleanField(default=False),
        ),
    ]
