# Generated by Django 6.0.4 on 2026-04-13 08:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_billing_defaults(apps, schema_editor):
    BillingConfiguration = apps.get_model("finance", "BillingConfiguration")
    PaymentPlan = apps.get_model("finance", "PaymentPlan")

    if not BillingConfiguration.objects.exists():
        BillingConfiguration.objects.create(
            registration_fee_name="Registration Fee",
            registration_fee_amount=Decimal("60.00"),
            registration_bonus_text="1 free training jersey",
            registration_description="Mandatory one-time onboarding fee charged when a student joins the academy.",
            payment_portal_note="Scan the QR code, transfer the exact amount, then upload a screenshot for admin verification.",
        )

    PaymentPlan.objects.update_or_create(
        code="monthly_4",
        defaults={
            "name": "Monthly Package - 4 Sessions",
            "sessions_per_month": 4,
            "monthly_fee": Decimal("100.00"),
            "description": "Recommended for weekly training rhythm and steady fundamentals.",
            "is_active": True,
            "is_default": True,
            "sort_order": 1,
        },
    )
    PaymentPlan.objects.update_or_create(
        code="monthly_8",
        defaults={
            "name": "Monthly Package - 8 Sessions",
            "sessions_per_month": 8,
            "monthly_fee": Decimal("160.00"),
            "description": "Best for players who want a higher-volume training schedule each month.",
            "is_active": True,
            "is_default": False,
            "sort_order": 2,
        },
    )
    PaymentPlan.objects.exclude(code="monthly_4").update(is_default=False)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_update_standard_fee_amounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee_name', models.CharField(default='Registration Fee', max_length=120)),
                ('registration_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=10)),
                ('registration_bonus_text', models.CharField(blank=True, default='1 free training jersey', max_length=255)),
                ('registration_description', models.TextField(blank=True, default='Mandatory one-time onboarding fee charged when a student joins the academy.')),
                ('payment_portal_note', models.TextField(blank=True, default='Scan the QR code, transfer the exact amount, then upload a screenshot for admin verification.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_billing_configuration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing configuration',
                'verbose_name_plural': 'Billing configuration',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(unique=True)),
                ('sessions_per_month', models.PositiveIntegerField(default=4)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payment_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'sessions_per_month', 'monthly_fee', 'name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finance.paymentplan'),
        ),
        migrations.RunPython(seed_billing_defaults, migrations.RunPython.noop),
    ]
