# Generated by Django 6.0.4 on 2026-04-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_billingconfiguration_paymentplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfiguration',
            name='trial_session_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
