# Generated by Django 6.0.4 on 2026-04-15 03:32

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_billingconfiguration_trial_session_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfiguration',
            name='opening_cash_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='branch_tag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending_verification', 'Pending Verification'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('rejected', 'Rejected')], default='unpaid', max_length=30),
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('expense_type', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], default='fixed', max_length=20)),
                ('category_tag', models.CharField(choices=[('rent', 'Rent'), ('software', 'Software'), ('salaries', 'Salaries'), ('equipment', 'Equipment'), ('events', 'Events'), ('transport', 'Transport'), ('marketing', 'Marketing'), ('utilities', 'Utilities'), ('tax', 'Tax'), ('other', 'Other')], default='other', max_length=30)),
                ('branch_tag', models.CharField(blank=True, max_length=255)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('card', 'Card'), ('ewallet', 'E-Wallet'), ('other', 'Other')], default='bank_transfer', max_length=30)),
                ('receipt_upload', models.FileField(blank=True, upload_to='expense_receipts/')),
                ('is_tax_deductible', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_model', models.CharField(max_length=120)),
                ('object_pk', models.CharField(max_length=64)),
                ('object_repr', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], default='updated', max_length=20)),
                ('period', models.DateField(blank=True, null=True)),
                ('branch_tag', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('happened_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-happened_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('student_count_change_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('revenue_drop_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('salary_increase_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('additional_coach_hires', models.PositiveIntegerField(default=0)),
                ('average_new_coach_monthly_cost', models.DecimalField(decimal_places=2, default=Decimal('2500.00'), max_digits=10)),
                ('new_branch_student_count', models.PositiveIntegerField(default=0)),
                ('new_branch_monthly_overhead', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('one_time_expansion_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('risk_buffer_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forecast_scenarios', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_forecast_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Use the first day of the locked month.', unique=True)),
                ('notes', models.TextField(blank=True)),
                ('is_closed', models.BooleanField(default=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Use the first day of the payroll month.')),
                ('branch_tag', models.CharField(blank=True, max_length=255)),
                ('base_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('per_session_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('session_count', models.PositiveIntegerField(default=0)),
                ('attendance_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payroll_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period', 'coach__username'],
                'constraints': [models.UniqueConstraint(fields=('coach', 'period', 'branch_tag'), name='unique_payroll_coach_period_branch')],
            },
        ),
    ]
