# Generated by Django 6.0.4 on 2026-04-12 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_systemflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='NYO Admin Dashboard', max_length=255)),
                ('hero_subtitle', models.TextField(default='Manage badminton club operations, parent billing, sessions, and role-based workflows from one connected system.')),
                ('announcement_text', models.CharField(default='Role-based club operations', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='support@nyo.local', max_length=254)),
                ('instagram_link', models.URLField(blank=True)),
                ('tiktok_link', models.URLField(blank=True)),
                ('primary_cta_text', models.CharField(default='Enter Parent Portal', max_length=100)),
                ('secondary_cta_text', models.CharField(default='Explore Role Flows', max_length=100)),
                ('available_programs', models.JSONField(blank=True, default=list)),
                ('available_locations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_landing_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Landing page content',
                'verbose_name_plural': 'Landing page content',
                'ordering': ['-updated_at'],
            },
        ),
    ]
