# Generated by Django 6.0.4 on 2026-04-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('coach', 'Coach'), ('headcount', 'Sales/Admin'), ('parent', 'Parent')], default='parent', max_length=20),
        ),
    ]
