# Generated by Django 6.0.4 on 2026-05-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_roles_superadmin_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='temporary_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
