# Generated by Django 6.0.4 on 2026-05-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_temporary_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='class_level',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='', help_text='Class level this coach handles. Empty for non-coach roles.', max_length=20),
        ),
    ]
