from django.urls import path

from finance.views import (
    BillingSettingsView,
    ComplianceView,
    ExpenseCreateView,
    ExpenseListView,
    ExpenseUpdateView,
    FinanceOverviewView,
    ForecastScenarioCreateView,
    ForecastScenarioListView,
    ForecastScenarioUpdateView,
    HistoricalLockCreateView,
    HistoricalLockUpdateView,
    InvoiceCreateView,
    InvoiceListView,
    InvoiceUpdateView,
    PaymentPlanCreateView,
    PaymentPlanDeleteView,
    PaymentPlanUpdateView,
    PayrollCreateView,
    PayrollListView,
    PayrollUpdateView,
    ProductCreateView,
    ProductDeleteView,
    ProductDetailView,
    ProductListView,
    ProductUpdateView,
    export_finance_csv,
)

app_name = "finance"

urlpatterns = [
    path("", FinanceOverviewView.as_view(), name="overview"),
    path("cash-flow/", FinanceOverviewView.as_view(), name="cash_flow"),
    path("billing/", BillingSettingsView.as_view(), name="billing_settings"),
    path("billing/plans/create/", PaymentPlanCreateView.as_view(), name="payment_plan_create"),
    path("billing/plans/<int:pk>/edit/", PaymentPlanUpdateView.as_view(), name="payment_plan_edit"),
    path("billing/plans/<int:pk>/delete/", PaymentPlanDeleteView.as_view(), name="payment_plan_delete"),
    path("invoices/", InvoiceListView.as_view(), name="invoice_list"),
    path("invoices/create/", InvoiceCreateView.as_view(), name="invoice_create"),
    path("invoices/<int:pk>/edit/", InvoiceUpdateView.as_view(), name="invoice_edit"),
    path("expenses/", ExpenseListView.as_view(), name="expense_list"),
    path("expenses/create/", ExpenseCreateView.as_view(), name="expense_create"),
    path("expenses/<int:pk>/edit/", ExpenseUpdateView.as_view(), name="expense_edit"),
    path("payroll/", PayrollListView.as_view(), name="payroll"),
    path("payroll/create/", PayrollCreateView.as_view(), name="payroll_create"),
    path("payroll/<int:pk>/edit/", PayrollUpdateView.as_view(), name="payroll_edit"),
    path("forecasting/", ForecastScenarioListView.as_view(), name="forecasting"),
    path("forecasting/create/", ForecastScenarioCreateView.as_view(), name="forecast_create"),
    path("forecasting/<int:pk>/edit/", ForecastScenarioUpdateView.as_view(), name="forecast_edit"),
    path("compliance/", ComplianceView.as_view(), name="compliance"),
    path("compliance/locks/create/", HistoricalLockCreateView.as_view(), name="historical_lock_create"),
    path("compliance/locks/<int:pk>/edit/", HistoricalLockUpdateView.as_view(), name="historical_lock_edit"),
    path("store/", ProductListView.as_view(), name="product_list"),
    path("store/create/", ProductCreateView.as_view(), name="product_create"),
    path("store/<int:pk>/", ProductDetailView.as_view(), name="product_detail"),
    path("store/<int:pk>/edit/", ProductUpdateView.as_view(), name="product_edit"),
    path("store/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"),
    path("export/csv/", export_finance_csv, name="export"),
]
