# Generated by Django 6.0.4 on 2026-04-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_admissionapplication_progressreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='playing_experience',
            field=models.CharField(choices=[('none', 'New to badminton'), ('school', 'School / recreational experience'), ('competitive', 'Competitive / tournament experience')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='primary_goal',
            field=models.CharField(choices=[('fundamentals', 'Build strong basics'), ('team', 'Prepare for school/team play'), ('competition', 'Train for competition')], default='fundamentals', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='recommended_level',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='training_frequency',
            field=models.CharField(choices=[('occasional', 'Just starting or occasional play'), ('weekly', 'Training 1-2 times per week'), ('intensive', 'Training 3+ times per week')], default='occasional', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='skill_level',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='basic', max_length=20),
        ),
    ]
