# Generated by Django 6.0.4 on 2026-04-13 08:45

import django.db.models.deletion
from django.db import migrations, models


def format_amount(amount):
    if amount == int(amount):
        return f"RM{int(amount)}"
    return f"RM{amount:.2f}"


def backfill_member_payment_plans(apps, schema_editor):
    BillingConfiguration = apps.get_model("finance", "BillingConfiguration")
    Invoice = apps.get_model("finance", "Invoice")
    PaymentPlan = apps.get_model("finance", "PaymentPlan")
    Member = apps.get_model("members", "Member")

    plans = {plan.code: plan for plan in PaymentPlan.objects.all()}
    default_plan = plans.get("monthly_4") or PaymentPlan.objects.order_by("sort_order", "id").first()
    high_volume_plan = plans.get("monthly_8") or default_plan
    billing_config = BillingConfiguration.objects.order_by("pk").first()
    registration_description = "Registration Fee"
    if billing_config:
        registration_description = billing_config.registration_fee_name
        if billing_config.registration_bonus_text:
            registration_description = f"{registration_description} (includes {billing_config.registration_bonus_text})"

    member_plan_map = {}
    for member in Member.objects.all().iterator():
        plan = plans.get(member.membership_type)
        if plan is None and member.membership_type == "monthly_8":
            plan = high_volume_plan
        if plan is None:
            plan = default_plan

        changed_fields = []
        if plan and member.payment_plan_id != plan.id:
            member.payment_plan_id = plan.id
            changed_fields.append("payment_plan")
        if plan and member.membership_type != plan.code:
            member.membership_type = plan.code
            changed_fields.append("membership_type")
        if changed_fields:
            member.save(update_fields=changed_fields)
        member_plan_map[member.pk] = plan

    for invoice in Invoice.objects.all().iterator():
        changed_fields = []
        linked_plan = invoice.payment_plan

        if invoice.invoice_type == "monthly":
            linked_plan = linked_plan or member_plan_map.get(invoice.member_id)
            if linked_plan and invoice.payment_plan_id != linked_plan.id:
                invoice.payment_plan_id = linked_plan.id
                changed_fields.append("payment_plan")
            if linked_plan:
                default_description = f"{linked_plan.name}: {format_amount(linked_plan.monthly_fee)} ({linked_plan.sessions_per_month} sessions per month)"
                if not invoice.description or invoice.description.startswith("Monthly package:") or invoice.description.startswith("Monthly Package -"):
                    invoice.description = default_description
                    changed_fields.append("description")
        elif invoice.invoice_type == "registration":
            if not invoice.description or "registration" in invoice.description.lower():
                invoice.description = registration_description
                changed_fields.append("description")

        if changed_fields:
            invoice.save(update_fields=changed_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_billingconfiguration_paymentplan_and_more'),
        ('members', '0004_membership_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='payment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='finance.paymentplan'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(blank=True, default='monthly_4', max_length=50),
        ),
        migrations.RunPython(backfill_member_payment_plans, migrations.RunPython.noop),
    ]
