# Generated by Django 6.0.4 on 2026-04-15 02:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_crm_data(apps, schema_editor):
    Member = apps.get_model("members", "Member")
    AdmissionApplication = apps.get_model("members", "AdmissionApplication")
    SyllabusRoot = apps.get_model("club_sessions", "SyllabusRoot")

    default_root = SyllabusRoot.objects.filter(is_default=True).first() or SyllabusRoot.objects.order_by("name").first()
    if default_root:
        Member.objects.filter(syllabus_root__isnull=True).update(syllabus_root=default_root)

    Member.objects.filter(status="suspended").update(status="inactive")
    AdmissionApplication.objects.filter(
        assigned_staff__isnull=True,
        reviewed_by__isnull=False,
    ).update(assigned_staff=models.F("reviewed_by"))


class Migration(migrations.Migration):

    dependencies = [
        ('club_sessions', '0006_syllabusroot_alter_syllabustemplate_options_and_more'),
        ('members', '0005_member_payment_plan_alter_member_membership_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_admission_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='interest_level',
            field=models.CharField(choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot')], default='warm', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='last_followed_up_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='next_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('walk_in', 'Walk-in'), ('other', 'Other')], default='website', max_length=30),
        ),
        migrations.AddField(
            model_name='member',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='churn_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='conversion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='last_contacted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='next_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='parent_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='program_enrolled',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='retention_risk_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='subscription_started_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='syllabus_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='club_sessions.syllabusroot'),
        ),
        migrations.AddField(
            model_name='member',
            name='trial_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='trial_linked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='trial_outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('converted', 'Converted'), ('no_show', 'No Show'), ('not_ready', 'Not Ready'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('inactive', 'Inactive'), ('churned', 'Churned')], default='active', max_length=20),
        ),
        migrations.RunPython(backfill_crm_data, migrations.RunPython.noop),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Call'), ('email', 'Email'), ('internal', 'Internal')], default='whatsapp', max_length=20)),
                ('message_type', models.CharField(choices=[('follow_up', 'Follow Up'), ('trial', 'Trial Update'), ('payment', 'Payment Update'), ('retention', 'Retention'), ('churn', 'Churn'), ('note', 'General Note')], default='follow_up', max_length=20)),
                ('outcome', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('next_step', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='members.admissionapplication')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='members.member')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-happened_at', '-created_at'],
            },
        ),
    ]
